[Settings]
  ID = "ism-watershed-wellness-snapshot"

[build]
  base    = "./src/app/"
  publish = "./build/"
  command = "pushd ../.. && ./scripts/cibuild && popd"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
